"""rename area to liv_area

Revision ID: 1ddd4d478978
Revises: bf3b55ba106e
Create Date: 2026-02-26 15:48:12.473159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ddd4d478978'
down_revision: Union[str, Sequence[str], None] = 'bf3b55ba106e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('liv_area', sa.Float(), nullable=True))
    op.drop_column('properties', 'area')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('properties', 'liv_area')
    # ### end Alembic commands ###
