"""add building_type

Revision ID: 675f2a949f96
Revises: b2c9019dc08b
Create Date: 2026-02-26 17:36:34.820904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675f2a949f96'
down_revision: Union[str, Sequence[str], None] = 'b2c9019dc08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('building_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'building_type')
    # ### end Alembic commands ###
