"""add admin_fee floor and monthly_fee

Revision ID: b2c9019dc08b
Revises: 1ddd4d478978
Create Date: 2026-02-26 17:20:05.870746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c9019dc08b'
down_revision: Union[str, Sequence[str], None] = '1ddd4d478978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('admin_fee', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('monthly_fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'monthly_fee')
    op.drop_column('properties', 'floor')
    op.drop_column('properties', 'admin_fee')
    # ### end Alembic commands ###
